import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Providers } from "./providers";
import { Toaster } from "../@/components/ui/toaster";
import Footer from "./components/footer/Footer";

// import {NextUIProvider} from "@nextui-org/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en" className="no-scrollbar bg-black">
      <body className={inter.className} suppressHydrationWarning={true}>
      <Providers >
        {/* <NextUIProvider> */}
          {children}
          <Toaster />
        {/* </NextUIProvider> */}
      </Providers>
      </body>
    </html>
  );
}
//(Removed it)
//suppressHydrationWarning When there is a Mismatch of components 
// like Component is not adaptable to Dark mode then HydrationWarning will be there
//Added Recoil Root 
